version: "3.9"

services:

  postgres:

    image: postgres:16

    container_name: crypto_postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Crypto_Market

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:

    image: dpage/pgadmin4

    container_name: crypto_pgadmin

    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@crypto.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "5050:80"

    depends_on:
      - postgres

  etl:

    build: .

    container_name: crypto_etl

    depends_on:
      - postgres

    env_file:
      - .env

    volumes:
      - .:/app

    command: python -m app.Pipeline

volumes:

  postgres_data: