"""remove test column

Revision ID: 1882951f917f
Revises: bba1513156e9
Create Date: 2026-08-04 21:30:00.294143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1882951f917f'
down_revision: Union[str, Sequence[str], None] = 'bba1513156e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cryptocurrencies', sa.Column('test_column', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cryptocurrencies', 'test_column')
    # ### end Alembic commands ###
