"""initial schema

Revision ID: 937f9f027fae
Revises: 
Create Date: 2026-08-04 20:28:02.072898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937f9f027fae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_execution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('rows_extracted', sa.Integer(), nullable=False),
    sa.Column('rows_loaded', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_crypto_marketcap'), table_name='cryptocurrencies')
    op.drop_index(op.f('idx_crypto_rank'), table_name='cryptocurrencies')
    op.drop_index(op.f('idx_crypto_symbol'), table_name='cryptocurrencies')
    op.drop_index(op.f('idx_crypto_timestamp'), table_name='cryptocurrencies')
    op.create_index('idx_coin_symbol', 'cryptocurrencies', ['symbol'], unique=False)
    op.create_index('idx_etl_timestamp', 'cryptocurrencies', ['etl_timestamp'], unique=False)
    op.create_index('idx_market_cap', 'cryptocurrencies', ['market_cap'], unique=False)
    op.create_index('idx_market_rank', 'cryptocurrencies', ['market_cap_rank'], unique=False)
    op.create_unique_constraint(None, 'cryptocurrencies', ['coin_id'])
    op.create_check_constraint('ck_current_price', 'cryptocurrencies', 'current_price >= 0')
    op.create_check_constraint('ck_liquidity_ratio', 'cryptocurrencies', 'liquidity_ratio >= 0')
    op.create_check_constraint('ck_market_cap', 'cryptocurrencies', 'market_cap >= 0')
    op.create_check_constraint('ck_market_cap_rank', 'cryptocurrencies', 'market_cap_rank >= 1')
    op.create_check_constraint('ck_total_volume', 'cryptocurrencies', 'total_volume >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_total_volume', 'cryptocurrencies', type_='check')
    op.drop_constraint('ck_market_cap_rank', 'cryptocurrencies', type_='check')
    op.drop_constraint('ck_market_cap', 'cryptocurrencies', type_='check')
    op.drop_constraint('ck_liquidity_ratio', 'cryptocurrencies', type_='check')
    op.drop_constraint('ck_current_price', 'cryptocurrencies', type_='check')
    op.drop_constraint(None, 'cryptocurrencies', type_='unique')
    op.drop_index('idx_market_rank', table_name='cryptocurrencies')
    op.drop_index('idx_market_cap', table_name='cryptocurrencies')
    op.drop_index('idx_etl_timestamp', table_name='cryptocurrencies')
    op.drop_index('idx_coin_symbol', table_name='cryptocurrencies')
    op.create_index(op.f('idx_crypto_timestamp'), 'cryptocurrencies', ['etl_timestamp'], unique=False)
    op.create_index(op.f('idx_crypto_symbol'), 'cryptocurrencies', ['symbol'], unique=False)
    op.create_index(op.f('idx_crypto_rank'), 'cryptocurrencies', ['market_cap_rank'], unique=False)
    op.create_index(op.f('idx_crypto_marketcap'), 'cryptocurrencies', ['market_cap'], unique=False)
    op.drop_table('etl_execution')
    # ### end Alembic commands ###
