"""add test column

Revision ID: bba1513156e9
Revises: 937f9f027fae
Create Date: 2026-08-04 21:27:11.905879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba1513156e9'
down_revision: Union[str, Sequence[str], None] = '937f9f027fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_coin_symbol'), table_name='cryptocurrencies')
    op.create_index('idx_coin_id', 'cryptocurrencies', ['coin_id'], unique=False)
    op.create_index('idx_symbol', 'cryptocurrencies', ['symbol'], unique=False)
    op.create_index('idx_symbol_timestamp', 'cryptocurrencies', ['symbol', 'etl_timestamp'], unique=False)
    op.create_unique_constraint('uq_coin_snapshot', 'cryptocurrencies', ['coin_id', 'etl_timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_coin_snapshot', 'cryptocurrencies', type_='unique')
    op.drop_index('idx_symbol_timestamp', table_name='cryptocurrencies')
    op.drop_index('idx_symbol', table_name='cryptocurrencies')
    op.drop_index('idx_coin_id', table_name='cryptocurrencies')
    op.create_index(op.f('idx_coin_symbol'), 'cryptocurrencies', ['symbol'], unique=False)
    # ### end Alembic commands ###
